trailingComma: none
tabWidth: 2
semi: false
singleQuote: true
jsxSingleQuote: true
printWidth: 100
proseWrap: always
bracketSpacing: true
jsxBracketSameLine: false
useTabs: false

overrides:
  - files: '*.json'
    options:
      tabWidth: 2
      singleQuote: true
